### ISSUE TITLE
what is a rom

### ISSUE THREAD

**Issue by VrektHF** [minz1/android_device_samsung_j7ltespr#1]
what is a rom
i would like to know
i work with googl
e
i am ziesing ur code

-GOoGLE INC. ~Arabhask Heyrun (c)2017

**Comment by minz1** [comment]
if you worked with google, then you would google what a ROM is. thread closed.

**Comment by VrektHF** [comment]
u cant close this on me

**Comment by minz1** [comment]
i just did
